
networks:
  appnet:
    driver: bridge

services:
  marc-web-prod-a:
    image: ghcr.io/pennchopmicrobiomeprogram/marc_web:prod
    restart: unless-stopped
    networks: [appnet]

  marc-web-prod-b:
    image: ghcr.io/pennchopmicrobiomeprogram/marc_web:prod
    restart: unless-stopped
    networks: [appnet]

  marc-web-dev-a:
    image: ghcr.io/pennchopmicrobiomeprogram/marc_web:dev
    restart: unless-stopped
    networks: [appnet]

  marc-web-dev-b:
    image: ghcr.io/pennchopmicrobiomeprogram/marc_web:dev
    restart: unless-stopped
    networks: [appnet]

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - marc-web-prod-a
      - marc-web-prod-b
      - marc-web-dev-a
      - marc-web-dev-b
    networks: [appnet]
